#!/usr/bin/env python3
"""Generates the live-DB seed SQL from shared/seed-recipes.json.

Deterministic UUIDs continue the scheme the original 4-chef/6-recipe seed
used: chefs a0000000-0000-4000-8000-00000000000N, recipes
b0000000-0000-4000-8000-0000000000NN. Existing chefs (mika.eats,
theo_cooks, june.bakes, rafa.fuego = 001-004) are untouched; new chefs
start at 005. Existing recipes (001-006) are untouched; new recipes start
at 007.

Run: python3 scripts/generate-seed-sql.py > /tmp/seed.sql
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / "shared/seed-recipes.json").read_text())

EXISTING_CHEF_IDS = {
    "mika.eats": "a0000000-0000-4000-8000-000000000001",
    "theo_cooks": "a0000000-0000-4000-8000-000000000002",
    "june.bakes": "a0000000-0000-4000-8000-000000000003",
    "rafa.fuego": "a0000000-0000-4000-8000-000000000004",
}


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def sql_json(value) -> str:
    return sql_str(json.dumps(value, ensure_ascii=False))


def sql_text_array(items) -> str:
    inner = ",".join(s.replace("'", "''").replace('"', '""') for s in items)
    return "'{" + inner + "}'"


def main() -> None:
    new_chefs = [c for c in DATA["chefs"] if not c["existing"]]
    chef_ids = dict(EXISTING_CHEF_IDS)
    for i, chef in enumerate(new_chefs):
        chef_ids[chef["username"]] = f"a0000000-0000-4000-8000-00000000000{5 + i}"

    # shared/seed-recipes.json is the single source of truth for BOTH demo
    # mode (which renders every recipe) and the live-DB seed (which must
    # skip the original 6 — already live under their own deterministic
    # UUIDs — or a re-run would insert them a second time under new ids).
    new_recipes = [r for r in DATA["recipes"] if not r["id"].startswith("seed-")]

    recipe_ids = {}
    for i, r in enumerate(new_recipes):
        n = 7 + i
        recipe_ids[r["id"]] = f"b0000000-0000-4000-8000-{n:012d}"

    out = []
    out.append("-- Generated by scripts/generate-seed-sql.py — do not hand-edit.")
    out.append("-- Source of truth: shared/seed-recipes.json\n")

    # ---- New chefs (auth.users + profiles) ----
    out.append("-- New chef accounts (never used to sign in; same pattern as the original 4 seed chefs)")
    for chef in new_chefs:
        uid = chef_ids[chef["username"]]
        username = chef["username"]
        email = username.replace(".", "").replace("_", "") + "@seed.adaptable.internal"
        out.append(f"""insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  is_sso_user, is_anonymous, confirmation_token, recovery_token,
  email_change_token_new, email_change, created_at, updated_at
) values (
  '00000000-0000-0000-0000-000000000000', '{uid}', 'authenticated', 'authenticated',
  {sql_str(email)}, crypt('unused-seed-account-' || gen_random_uuid()::text, gen_salt('bf')),
  now(), '{{"provider":"email","providers":["email"]}}', {sql_json({"username": username})},
  false, false, '', '', '', '', now(), now()
) on conflict (id) do nothing;""")
        out.append(f"""insert into public.profiles (id, username, created_at)
values ('{uid}', {sql_str(username)}, now())
on conflict (id) do nothing;\n""")

    # ---- Recipes ----
    out.append("-- New recipes")
    for r in new_recipes:
        rid = recipe_ids[r["id"]]
        author_id = chef_ids[r["author"]]
        ingredients = [
            {k: v for k, v in ing.items() if v is not None} for ing in r["ingredients"]
        ]
        steps = [{k: v for k, v in s.items() if v is not None} for s in r["steps"]]
        out.append(f"""insert into public.recipes (
  id, author_id, title, description, emoji, cuisine, difficulty,
  prep_time_minutes, cook_time_minutes, servings, calories, protein_g, carbs_g, fat_g,
  tags, ingredients, steps, source_prompt, source_url,
  net_upvotes, cook_count, comment_count, created_at
) values (
  '{rid}', '{author_id}', {sql_str(r['title'])}, {sql_str(r['description'])},
  {sql_str(r['emoji'])}, {sql_str(r['cuisine'])}, {sql_str(r['difficulty'])},
  {r['prep_time_minutes']}, {r['cook_time_minutes']}, {r['servings']},
  {r['calories']}, {r['protein_g']}, {r['carbs_g']}, {r['fat_g']},
  {sql_text_array(r['tags'])}, {sql_json(ingredients)}::jsonb, {sql_json(steps)}::jsonb,
  {sql_str(r['source_prompt'])}, null,
  0, 0, 0, now() - interval '{r['days_ago']} days'
) on conflict (id) do nothing;""")

    # ---- Comments (drive comment_count via the incremental trigger) ----
    out.append("\n-- Review comments — inserted as real rows so comment_count and the")
    out.append("-- visible comment list always match (each insert increments comment_count by 1).")
    for r in new_recipes:
        rid = recipe_ids[r["id"]]
        n_comments = len(r["comments"])
        for i, c in enumerate(r["comments"]):
            author_id = chef_ids[c["author"]]
            frac = (i + 1) / (n_comments + 1)
            out.append(
                f"insert into public.comments (recipe_id, user_id, body, created_at) values "
                f"('{rid}', '{author_id}', {sql_str(c['body'])}, "
                f"now() - interval '{r['days_ago']} days' + "
                f"(interval '{r['days_ago']} days' * {frac:.4f}));"
            )

    # ---- Baseline social-proof counters (net_upvotes / cook_count) ----
    # These are set directly (not via hundreds of fake vote/cook rows — the
    # unique (user_id, recipe_id) constraint on user_votes caps real votes
    # at the number of distinct profiles anyway). The incremental trigger
    # migration (20260705000000) means real future engagement adds to these
    # baselines correctly instead of recomputing them away.
    out.append("\n-- Baseline social-proof counters")
    for r in new_recipes:
        rid = recipe_ids[r["id"]]
        out.append(
            f"update public.recipes set net_upvotes = {r['net_upvotes']}, "
            f"cook_count = {r['cook_count']} where id = '{rid}';"
        )

    print("\n".join(out))


if __name__ == "__main__":
    main()
